version: "3"
services:
  envoy:
    image: envoyproxy/envoy-dev:e4955aed5694f9935d674419dbb364e744f697b4
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml #change to /etc/envoy/envoy.yaml if you are using envoy.yaml
    ports:
      - "9901:9901" #port 9901 on host connected to port 9901 on envoy
      - "8000:8000" #port 9901 on host connected to port 9901 on envoy
    network_mode: "host"

  redis:
    image: bitnami/redis
    volumes:
      - redis_data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
volumes:
  redis_data: